from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('about/', views.about_view, name="about"),
    path('contactus/', views.contactus_view, name="contactus"),
    path('forgotpassword/', views.forgotpassword, name="forgot_password"),
    path('termsandconditions/', views.termsandconditions_view, name="termsandconditions"),
    path("help_center/", views.help_center, name="help_center"),
    path("careers/", views.careers, name="careers"),
    path("faq/", views.faq, name="faq"),
    path("subscriptions/", views.subscriptions, name="subscriptions"),
    path("product/", views.product_view, name="product"),
    path("accessbility/", views.accessbility_view, name="accessbility"),
    path("cookie_policy/", views.cookie_policy, name="cookie_policy"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path('404/', views.error_404_view, name='error_404'),
    path("blog/", views.blog_view, name="blog"),
    path("media/", views.media_view, name="media"),
    path("whyus/", views.whyus_view, name="whyus"),
    path("events/", views.events_view, name="events"),
    path("clients/", views.clients_view, name="clients"),
    path("mission/", views.mission_view, name="mission"),
    path("documentation/", views.documentation_view, name="documentation"),
    path("reports/", views.reports_view, name="reports"),
    path('dashboard/', views.dashboard_view, name="dashboard"),
    path("add/", views.add, name="add"),
    path("sub/", views.sub, name="sub"),
    path("multi/", views.multi, name="multi"),
    path("div/", views.div, name="div"),
    path("modulus/", views.modulus, name="modulus"),
    path("floordivision/", views.floordivision, name="floordivision"),
]
